version: '3.8'

services:
  postgres:
    container_name: test-postgres
    image: postgres
    ports:
      - 5436:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: test-node
      PGDATA: /data/postgres
